export const entrada = [
  {
    id: "1",
    multer: "entrada1",
    preguntaForm: "en1",
    pregunta_nombre: "Se encuentra totem/cartel de mes vigente",
    checkbox: "entradacheckbox1",
    comentario: "entradacomentario1",
    fecha: "entradafecha1",
    entradaValor: "entradaValor1",
  },
  {
    id: "2",
    multer: "entrada2",
    preguntaForm: "en2",
    pregunta_nombre: "T-rack con campaña vigente",
    checkbox: "entradacheckbox2",
    comentario: "entradacomentario2",
    fecha: "entradafecha2",
    entradaValor: "entradaValor2",
  },
  {
    id: "3",
    multer: "entrada3",
    preguntaForm: "en3",
    pregunta_nombre: "Carros y canastas de servicio disponibles",
    checkbox: "entradacheckbox3",
    comentario: "entradacomentario3",
    fecha: "entradafecha3",
    entradaValor: "entradaValor3",
  },
  {
    id: "4",
    multer: "entrada4",
    preguntaForm: "en4",
    pregunta_nombre: "Tapete petco colocado y limpio",
    checkbox: "entradacheckbox4",
    comentario: "entradacomentario4",
    fecha: "entradafecha4",
    entradaValor: "entradaValor4",
  },
  {
    id: "5",
    multer: "entrada5",
    preguntaForm: "en5",
    pregunta_nombre: "Botes de basura limpios",
    checkbox: "entradacheckbox5",
    comentario: "entradacomentario5",
    fecha: "entradafecha5",
    entradaValor: "entradaValor5",
  },
];
export const checkOut = [
  {
    id: "1",
    multer: "checkout1",
    preguntaForm: "ch1",
    pregunta_nombre: "Producto adoptado vigente",
    checkbox: "checkoutcheckbox1",
    comentario: "checkcomentario1",
    fecha: "checkfecha1",
    checkoutValor: "checkoutValor1",
  },
  {
    id: "2",
    multer: "checkout2",
    preguntaForm: "ch2",
    pregunta_nombre: "Producto adoptado señalizado",
    checkbox: "checkoutcheckbox2",
    comentario: "checkcomentario2",
    fecha: "checkfecha2",
    checkoutValor: "checkoutValor2",
  },
  {
    id: "3",
    multer: "checkout3",
    preguntaForm: "ch3",
    pregunta_nombre: "Unifila con producto autorizado",
    checkbox: "checkoutcheckbox3",
    comentario: "checkcomentario3",
    fecha: "checkfecha3",
    checkoutValor: "checkoutValor3",
  },
  {
    id: "4",
    multer: "checkout4",
    preguntaForm: "ch4",
    pregunta_nombre: "Bolsas reutilizabes exhibidas",
    checkbox: "checkoutcheckbox4",
    comentario: "checkcomentario4",
    fecha: "checkfecha4",
    checkoutValor: "checkoutValor4",
  },
  {
    id: "5",
    multer: "checkout5",
    preguntaForm: "ch5",
    pregunta_nombre: "Botadero 2*99/temporada",
    checkbox: "checkoutcheckbox5",
    comentario: "checkcomentario5",
    fecha: "checkfecha5",
    checkoutValor: "checkoutValor5",
  },
  {
    id: "6",
    multer: "checkout6",
    preguntaForm: "ch6",
    pregunta_nombre: "Sin mesas y/o botaderos de liquidación",
    checkbox: "checkoutcheckbox6",
    comentario: "checkcomentario6",
    fecha: "checkfecha6",
    checkoutValor: "checkoutValor6",
  },
  {
    id: "7",
    multer: "checkout7",
    preguntaForm: "ch7",
    pregunta_nombre: "Carritos de servicio exclusivos para uso de clientes",
    checkbox: "checkoutcheckbox7",
    comentario: "checkcomentario7",
    fecha: "checkfecha7",
    checkoutValor: "checkoutValor7",
  },
  {
    id: "8",
    multer: "checkout8",
    preguntaForm: "ch8",
    pregunta_nombre: "Cajas funcionando acorde a volumen de clientes",
    checkbox: "checkoutcheckbox8",
    comentario: "checkcomentario8",
    fecha: "checkfecha8",
    checkoutValor: "checkoutValor8",
  },
];
export const exhibiciones = [
  {
    id: "1",
    multer: "exhi1",
    preguntaForm: "ex1",
    pregunta_nombre: "Exhibiciones de mes autorizadas",
    checkbox: "exhicheckbox1",
    comentario: "exhicomentario1",
    fecha: "exhifecha1",
    exhibicionesValor: "exhibicionesValor1",
  },
  {
    id: "2",
    multer: "exhi2",
    preguntaForm: "ex2",
    pregunta_nombre: "Señalización vigente en exhibición",
    checkbox: "exhicheckbox2",
    comentario: "exhicomentario2",
    fecha: "exhifecha2",
    exhibicionesValor: "exhibicionesValor2",
  },
  {
    id: "3",
    multer: "exhi3",
    preguntaForm: "ex3",
    pregunta_nombre: "Respeta lineamientos",
    checkbox: "exhicheckbox3",
    comentario: "exhicomentario3",
    fecha: "exhifecha3",
    exhibicionesValor: "exhibicionesValor3",
  },
];
export const nutricion = [
  {
    id: "1",
    multer: "nutri1",
    preguntaForm: "nut1",
    pregunta_nombre: "Floorplan coincide físico vs PDF",
    checkbox: "nutricheckbox1",
    comentario: "nutricomentario1",
    fecha: "nutrifecha1",
    nutricionValor: "nutrivalor1",
  },
  {
    id: "2",
    multer: "nutri2",
    preguntaForm: "nut2",
    pregunta_nombre: "Montaje de cabeceras vigentes en floorplan",
    checkbox: "nutricheckbox2",
    comentario: "nutricomentario2",
    fecha: "nutrifecha2",
    nutricionValor: "nutrivalor2",
  },
  {
    id: "3",
    multer: "nutri3",
    preguntaForm: "nut3",
    pregunta_nombre: "Dueño de cabeceras vigentes en flooplan",
    checkbox: "nutricheckbox3",
    comentario: "nutricomentario3",
    fecha: "nutrifecha3",
    nutricionValor: "nutrivalor3",
  },
];
export const alimentoNatural = [
  {
    id: "A)",
    multer: "nutri4",
    preguntaForm: "nut4",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "nutricheckbox4",
    comentario: "nutricomentario4",
    fecha: "nutrifecha4",
    nutricionValor: "nutrivalor4",
  },
  {
    id: "B)",
    multer: "nutri5",
    preguntaForm: "nut5",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "nutricheckbox5",
    comentario: "nutricomentario5",
    fecha: "nutrifecha5",
    nutricionValor: "nutrivalor5",
  },
  {
    id: "C)",
    multer: "nutri6",
    preguntaForm: "nut6",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "nutricheckbox6",
    comentario: "nutricomentario6",
    fecha: "nutrifecha6",
    nutricionValor: "nutrivalor6",
  },
  {
    id: "D)",
    multer: "nutri7",
    preguntaForm: "nut7",
    pregunta_nombre: "Planchado de bultos es correcto",
    checkbox: "nutricheckbox7",
    comentario: "nutricomentario7",
    fecha: "nutrifecha7",
    nutricionValor: "nutrivalor7",
  },
  {
    id: "E)",
    multer: "nutri8",
    preguntaForm: "nut8",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "nutricheckbox8",
    comentario: "nutricomentario8",
    fecha: "nutrifecha8",
    nutricionValor: "nutrivalor8",
  },
  {
    id: "F)",
    multer: "nutri9",
    preguntaForm: "nut9",
    pregunta_nombre: "Punteo de caducidades de productos en tramos",
    checkbox: "nutricheckbox9",
    comentario: "nutricomentario9",
    fecha: "nutrifecha9",
    nutricionValor: "nutrivalor9",
  },
  {
    id: "G)",
    multer: "nutri10",
    preguntaForm: "nut10",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "nutricheckbox10",
    comentario: "nutricomentario10",
    fecha: "nutrifecha10",
    nutricionValor: "nutrivalor10",
  },
  {
    id: "H)",
    multer: "nutri11",
    preguntaForm: "nut11",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "nutricheckbox11",
    comentario: "nutricomentario11",
    fecha: "nutrifecha11",
    nutricionValor: "nutrivalor11",
  },
  {
    id: "I)",
    multer: "nutri12",
    preguntaForm: "nut12",
    pregunta_nombre: "Tiras de impulso colocadas acorde a POG/Guía",
    checkbox: "nutricheckbox12",
    comentario: "nutricomentario12",
    fecha: "nutrifecha12",
    nutricionValor: "nutrivalor12",
  },
  {
    id: "J)",
    multer: "nutri13",
    preguntaForm: "nut13",
    pregunta_nombre: "Balcones de alimento colocados/mercadeados",
    checkbox: "nutricheckbox13",
    comentario: "nutricomentario13",
    fecha: "nutrifecha13",
    nutricionValor: "nutrivalor13",
  },
  {
    id: "K)",
    multer: "nutri14",
    preguntaForm: "nut14",
    pregunta_nombre: "Refrigerador mercadeado y sin sobre stock",
    checkbox: "nutricheckbox14",
    comentario: "nutricomentario14",
    fecha: "nutrifecha14",
    nutricionValor: "nutrivalor14",
  },
];
export const alimentoAvanzado = [
  {
    id: "A)",
    multer: "nutri15",
    preguntaForm: "nut15",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "nutricheckbox15",
    comentario: "nutricomentario15",
    fecha: "nutrifecha15",
    nutricionValor: "nutrivalor15",
  },
  {
    id: "B)",
    multer: "nutri16",
    preguntaForm: "nut16",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "nutricheckbox16",
    comentario: "nutricomentario16",
    fecha: "nutrifecha16",
    nutricionValor: "nutrivalor16",
  },
  {
    id: "C)",
    multer: "nutri17",
    preguntaForm: "nut17",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "nutricheckbox17",
    comentario: "nutricomentario17",
    fecha: "nutrifecha17",
    nutricionValor: "nutrivalor17",
  },
  {
    id: "D)",
    multer: "nutri18",
    preguntaForm: "nut18",
    pregunta_nombre: "Planchado de bultos es correcto",
    checkbox: "nutricheckbox18",
    comentario: "nutricomentario18",
    fecha: "nutrifecha18",
    nutricionValor: "nutrivalor18",
  },
  {
    id: "E)",
    multer: "nutri19",
    preguntaForm: "nut19",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "nutricheckbox19",
    comentario: "nutricomentario19",
    fecha: "nutrifecha19",
    nutricionValor: "nutrivalor19",
  },
  {
    id: "F)",
    multer: "nutri20",
    preguntaForm: "nut20",
    pregunta_nombre: "Punteo de caducidades de producto en tramos",
    checkbox: "nutricheckbox20",
    comentario: "nutricomentario20",
    fecha: "nutrifecha20",
    nutricionValor: "nutrivalor20",
  },
  {
    id: "G)",
    multer: "nutri21",
    preguntaForm: "nut21",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "nutricheckbox21",
    comentario: "nutricomentario21",
    fecha: "nutrifecha21",
    nutricionValor: "nutrivalor21",
  },
  {
    id: "H)",
    multer: "nutri22",
    preguntaForm: "nut22",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "nutricheckbox22",
    comentario: "nutricomentario22",
    fecha: "nutrifecha22",
    nutricionValor: "nutrivalor22",
  },
  {
    id: "I)",
    multer: "nutri23",
    preguntaForm: "nut23",
    pregunta_nombre: "Tiras de impulso colocadas acorde a POG",
    checkbox: "nutricheckbox23",
    comentario: "nutricomentario23",
    fecha: "nutrifecha23",
    nutricionValor: "nutrivalor23",
  },
  {
    id: "J)",
    multer: "nutri24",
    preguntaForm: "nut24",
    pregunta_nombre: "Balcones de alimento colocados/mercadeados",
    checkbox: "nutricheckbox24",
    comentario: "nutricomentario24",
    fecha: "nutrifecha24",
    nutricionValor: "nutrivalor24",
  },
];
export const alimentoPrescripcion = [
  {
    id: "A)",
    multer: "nutri25",
    preguntaForm: "nut25",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "nutricheckbox25",
    comentario: "nutricomentario25",
    fecha: "nutrifecha25",
    nutricionValor: "nutrivalor25",
  },
  {
    id: "B)",
    multer: "nutri26",
    preguntaForm: "nut26",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "nutricheckbox26",
    comentario: "nutricomentario26",
    fecha: "nutrifecha26",
    nutricionValor: "nutrivalor26",
  },
  {
    id: "C)",
    multer: "nutri27",
    preguntaForm: "nut27",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "nutricheckbox27",
    comentario: "nutricomentario27",
    fecha: "nutrifecha27",
    nutricionValor: "nutrivalor27",
  },
  {
    id: "D)",
    multer: "nutri28",
    preguntaForm: "nut28",
    pregunta_nombre: "Planchado de bultos es correcto",
    checkbox: "nutricheckbox28",
    comentario: "nutricomentario28",
    fecha: "nutrifecha28",
    nutricionValor: "nutrivalor28",
  },
  {
    id: "E)",
    multer: "nutri29",
    preguntaForm: "nut29",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "nutricheckbox29",
    comentario: "nutricomentario29",
    fecha: "nutrifecha29",
    nutricionValor: "nutrivalor29",
  },
  {
    id: "F)",
    multer: "nutri30",
    preguntaForm: "nut30",
    pregunta_nombre: "Punteo de caducidades de productos en tramos",
    checkbox: "nutricheckbox30",
    comentario: "nutricomentario30",
    fecha: "nutrifecha30",
    nutricionValor: "nutrivalor30",
  },
  {
    id: "G)",
    multer: "nutri31",
    preguntaForm: "nut31",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "nutricheckbox31",
    comentario: "nutricomentario31",
    fecha: "nutrifecha31",
    nutricionValor: "nutrivalor31",
  },
  {
    id: "H)",
    multer: "nutri32",
    preguntaForm: "nut32",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "nutricheckbox32",
    comentario: "nutricomentario32",
    fecha: "nutrifecha32",
    nutricionValor: "nutrivalor32",
  },
  {
    id: "I)",
    multer: "nutri33",
    preguntaForm: "nut33",
    pregunta_nombre: "Tiras de impulso colocadas acorde a POG/Guía",
    checkbox: "nutricheckbox33",
    comentario: "nutricomentario33",
    fecha: "nutrifecha33",
    nutricionValor: "nutrivalor33",
  },
];
export const premiosCarMas = [
  {
    id: "A)",
    multer: "nutri34",
    preguntaForm: "nut34",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "nutricheckbox34",
    comentario: "nutricomentario34",
    fecha: "nutrifecha34",
    nutricionValor: "nutrivalor34",
  },
  {
    id: "B)",
    multer: "nutri35",
    preguntaForm: "nut35",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "nutricheckbox35",
    comentario: "nutricomentario35",
    fecha: "nutrifecha35",
    nutricionValor: "nutrivalor35",
  },
  {
    id: "C)",
    multer: "nutri36",
    preguntaForm: "nut36",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "nutricheckbox36",
    comentario: "nutricomentario36",
    fecha: "nutrifecha36",
    nutricionValor: "nutrivalor36",
  },
  {
    id: "D)",
    multer: "nutri37",
    preguntaForm: "nut37",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "nutricheckbox37",
    comentario: "nutricomentario37",
    fecha: "nutrifecha37",
    nutricionValor: "nutrivalor37",
  },
  {
    id: "E)",
    multer: "nutri38",
    preguntaForm: "nut38",
    pregunta_nombre: "Punteo de caducidades de producto en tramos",
    checkbox: "nutricheckbox38",
    comentario: "nutricomentario38",
    fecha: "nutrifecha38",
    nutricionValor: "nutrivalor38",
  },
  {
    id: "F)",
    multer: "nutri39",
    preguntaForm: "nut39",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "nutricheckbox39",
    comentario: "nutricomentario39",
    fecha: "nutrifecha39",
    nutricionValor: "nutrivalor39",
  },
  {
    id: "G)",
    multer: "nutri40",
    preguntaForm: "nut40",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "nutricheckbox40",
    comentario: "nutricomentario40",
    fecha: "nutrifecha40",
    nutricionValor: "nutrivalor40",
  },
];
export const nutriCSN = [
  {
    id: "1",
    multer: "nutri41",
    preguntaForm: "nut41",
    pregunta_nombre: "Se solicita al área de categorías",
    checkbox: "nutricheckbox41",
    comentario: "nutricomentario41",
    fecha: "nutrifecha41",
  },
  {
    id: "2",
    multer: "nutri42",
    preguntaForm: "nut42",
    pregunta_nombre: "Se solicita al área de abasto",
    checkbox: "nutricheckbox42",
    comentario: "nutricomentario42",
    fecha: "nutrifecha42",
  },
  {
    id: "3",
    multer: "nutri43",
    preguntaForm: "nut43",
    pregunta_nombre: "Se solicita al área de marketing",
    checkbox: "nutricheckbox43",
    comentario: "nutricomentario43",
    fecha: "nutrifecha43",
  },
  {
    id: "4",
    multer: "nutri44",
    preguntaForm: "nut44",
    pregunta_nombre: "Se solicita al área de compras",
    checkbox: "nutricheckbox44",
    comentario: "nutricomentario44",
    fecha: "nutrifecha44",
  },
  {
    id: "5",
    multer: "nutri45",
    preguntaForm: "nut45",
    pregunta_nombre: "Se solicita al área de consumo interno",
    checkbox: "nutricheckbox45",
    comentario: "nutricomentario45",
    fecha: "nutrifecha45",
  },
  {
    id: "6",
    multer: "nutri46",
    preguntaForm: "nut46",
    pregunta_nombre: "Se solicita al área de recursos humanos",
    checkbox: "nutricheckbox46",
    comentario: "nutricomentario46",
    fecha: "nutrifecha46",
  },
];
export const saludBienestar = [
  {
    id: "1",
    multer: "salud1",
    preguntaForm: "sal1",
    pregunta_nombre: "Floorplan coincide físico vs PDF",
    checkbox: "saludcheckbox1",
    comentario: "saludcomentario1",
    fecha: "saludfecha1",
    saludValor: "saludValor1",
  },
  {
    id: "2",
    multer: "salud2",
    preguntaForm: "sal2",
    pregunta_nombre: "Montaje de cabeceras vigentes en floorplan",
    checkbox: "saludcheckbox2",
    comentario: "saludcomentario2",
    fecha: "saludfecha2",
    saludValor: "saludValor2",
  },
  {
    id: "3",
    multer: "salud3",
    preguntaForm: "sal3",
    pregunta_nombre: "Dueño de pasillo ejecutando tareas",
    checkbox: "saludcheckbox3",
    comentario: "saludcomentario3",
    fecha: "saludfecha3",
    saludValor: "saludValor3",
  },
];
export const POGSbelleza = [
  {
    id: "A)",
    multer: "salud4",
    preguntaForm: "sal4",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "saludcheckbox4",
    comentario: "saludcomentario4",
    fecha: "saludfecha4",
    saludValor: "saludValor4",
  },
  {
    id: "B)",
    multer: "salud5",
    preguntaForm: "sal5",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "saludcheckbox5",
    comentario: "saludcomentario5",
    fecha: "saludfecha5",
    saludValor: "saludValor5",
  },
  {
    id: "C)",
    multer: "salud6",
    preguntaForm: "sal6",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "saludcheckbox6",
    comentario: "saludcomentario6",
    fecha: "saludfecha6",
    saludValor: "saludValor6",
  },
  {
    id: "D)",
    multer: "salud7",
    preguntaForm: "sal7",
    pregunta_nombre: "Punteo de caducidades de producto en tramos",
    checkbox: "saludcheckbox7",
    comentario: "saludcomentario7",
    fecha: "saludfecha7",
    saludValor: "saludValor7",
  },
  {
    id: "E)",
    multer: "salud8",
    preguntaForm: "sal8",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "saludcheckbox8",
    comentario: "saludcomentario8",
    fecha: "saludfecha8",
    saludValor: "saludValor8",
  },
  {
    id: "F)",
    multer: "salud9",
    preguntaForm: "sa9",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "saludcheckbox9",
    comentario: "saludcomentario9",
    fecha: "saludfecha9",
    saludValor: "saludValor9",
  },
  {
    id: "G)",
    multer: "salud10",
    preguntaForm: "sal10",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "saludcheckbox10",
    comentario: "saludcomentario10",
    fecha: "saludfecha10",
    saludValor: "saludValor10",
  },
];
export const POGSsalud = [
  {
    id: "A)",
    multer: "salud11",
    preguntaForm: "sa11",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "saludcheckbox11",
    comentario: "saludcomentario11",
    fecha: "saludfecha11",
    saludValor: "saludValor11",
  },
  {
    id: "B)",
    multer: "salud12",
    preguntaForm: "sal12",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "saludcheckbox12",
    comentario: "saludcomentario12",
    fecha: "saludfecha12",
    saludValor: "saludValor12",
  },
  {
    id: "C)",
    multer: "salud13",
    preguntaForm: "sal13",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "saludcheckbox13",
    comentario: "saludcomentario13",
    fecha: "saludfecha13",
    saludValor: "saludValor13",
  },
  {
    id: "D)",
    multer: "salud14",
    preguntaForm: "sal14",
    pregunta_nombre: "Punteo de caducidades de producto en tramos",
    checkbox: "saludcheckbox14",
    comentario: "saludcomentario14",
    fecha: "saludfecha14",
    saludValor: "saludValor14",
  },
  {
    id: "E)",
    multer: "salud15",
    preguntaForm: "sal15",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "saludcheckbox15",
    comentario: "saludcomentario15",
    fecha: "saludfecha15",
    saludValor: "saludValor15",
  },
  {
    id: "F)",
    multer: "salud16",
    preguntaForm: "sal16",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "saludcheckbox16",
    comentario: "saludcomentario16",
    fecha: "saludfecha16",
    saludValor: "saludValor16",
  },
  {
    id: "G)",
    multer: "salud17",
    preguntaForm: "sal17",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "saludcheckbox17",
    comentario: "saludcomentario17",
    fecha: "saludfecha17",
    saludValor: "saludValor17",
  },
];
export const POGSlimpieza = [
  {
    id: "A)",
    multer: "salud18",
    preguntaForm: "sal18",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "saludcheckbox18",
    comentario: "saludcomentario18",
    fecha: "saludfecha18",
    saludValor: "saludValor18",
  },
  {
    id: "B)",
    multer: "salud19",
    preguntaForm: "sal19",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "saludcheckbox19",
    comentario: "saludcomentario19",
    fecha: "saludfecha19",
    saludValor: "saludValor19",
  },
  {
    id: "C)",
    multer: "salud20",
    preguntaForm: "sal20",
    pregunta_nombre: " Planogramas colocados en tramos",
    checkbox: "saludcheckbox20",
    comentario: "saludcomentario20",
    fecha: "saludfecha20",
    saludValor: "saludValor20",
  },
  {
    id: "D)",
    multer: "salud21",
    preguntaForm: "sal21",
    pregunta_nombre: "Punteo de caducidades de producto en tramos",
    checkbox: "saludcheckbox21",
    comentario: "saludcomentario21",
    fecha: "saludfecha21",
    saludValor: "saludValor21",
  },
  {
    id: "E)",
    multer: "salud22",
    preguntaForm: "sa22",
    pregunta_nombre: "Arenero granel limpio, con garrafas correspondientes ",
    checkbox: "saludcheckbox22",
    comentario: "saludcomentario22",
    fecha: "saludfecha22",
    saludValor: "saludValor22",
  },
  {
    id: "F)",
    multer: "salud23",
    preguntaForm: "sal23",
    pregunta_nombre:
      "Tarima arena a granel con señalización y altura permitida",
    checkbox: "saludcheckbox23",
    comentario: "saludcomentario23",
    fecha: "saludfecha23",
    saludValor: "saludValor23",
  },
  {
    id: "G)",
    multer: "salud24",
    preguntaForm: "sal24",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "saludcheckbox24",
    comentario: "saludcomentario24",
    fecha: "saludfecha24",
    saludValor: "saludValor24",
  },
  {
    id: "H)",
    multer: "salud25",
    preguntaForm: "sal25",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "saludcheckbox25",
    comentario: "saludcomentario25",
    fecha: "saludfecha25",
    saludValor: "saludValor25",
  },
  {
    id: "I)",
    multer: "salud26",
    preguntaForm: "sal26",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "saludcheckbox26",
    comentario: "saludcomentario26",
    fecha: "saludfecha26",
    saludValor: "saludValor26",
  },
];
export const POGSCSN = [
  {
    id: "1",
    multer: "salud27",
    preguntaForm: "sal27",
    pregunta_nombre: "Se solicita al área de categorías",
    checkbox: "saludcheckbox27",
    comentario: "saludcomentario27",
    fecha: "saludfecha27",
  },
  {
    id: "2",
    multer: "salud28",
    preguntaForm: "sal28",
    pregunta_nombre: "Se solicita al área de abasto",
    checkbox: "saludcheckbox28",
    comentario: "saludcomentario28",
    fecha: "saludfecha28",
  },
  {
    id: "3",
    multer: "salud29",
    preguntaForm: "sal29",
    pregunta_nombre: "Se solicita al área de marketing",
    checkbox: "saludcheckbox29",
    comentario: "saludcomentario29",
    fecha: "saludfecha29",
  },
  {
    id: "4",
    multer: "salud30",
    preguntaForm: "sal30",
    pregunta_nombre: "Se solicita al área de compras",
    checkbox: "saludcheckbox30",
    comentario: "saludcomentro30",
    fecha: "saludfecha30",
  },
  {
    id: "5",
    multer: "salud31",
    preguntaForm: "sal31",
    pregunta_nombre:
      "Se solicita al área de consumo internobiliario/Cunsumo interno",
    checkbox: "saludcheckbox31",
    comentario: "saludcomentario31",
    fecha: "saludfecha31",
  },
  {
    id: "6",
    multer: "salud32",
    preguntaForm: "sal32",
    pregunta_nombre: "Se solicita al área de recursos humanos",
    checkbox: "saludcheckbox32",
    comentario: "saludcomentario32",
    fecha: "saludfecha32",
  },
];
export const ModaDiversion = [
  {
    id: "1",
    multer: "moda1",
    preguntaForm: "mod1",
    pregunta_nombre: "Floorplan coincide físico vs PDF",
    checkbox: "modacheckbox1",
    comentario: "modacomentario1",
    fecha: "modafecha1",
    modaValor: "modaValor1",
  },
  {
    id: "2",
    multer: "moda2",
    preguntaForm: "mod2",
    pregunta_nombre: "Dueño de pasillo ejecutando tareas",
    checkbox: "modacheckbox2",
    comentario: "modacomentario2",
    fecha: "modafecha2",
    modaValor: "modaValor2",
  },
  {
    id: "3",
    multer: "moda3",
    preguntaForm: "mod3",
    pregunta_nombre: "Montaje de seasonal a POG/Guí­a flex",
    checkbox: "modacheckbox3",
    comentario: "modacomentario3",
    fecha: "modafecha3",
    modaValor: "modaValor3",
  },
  {
    id: "4",
    multer: "moda4",
    preguntaForm: "mod4",
    pregunta_nombre: "Montaje de cabeceras vigentes en floorplan",
    checkbox: "modacheckbox4",
    comentario: "modacomentario4",
    fecha: "modafecha4",
    modaValor: "modaValor4",
  },
];
export const planomdperro = [
  {
    id: "A)",
    multer: "moda5",
    preguntaForm: "mod5",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "modacheckbox5",
    comentario: "modacomentario5",
    fecha: "modafecha15",
    modaValor: "modaValor5",
  },
  {
    id: "B)",
    multer: "moda6",
    preguntaForm: "mod6",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "modacheckbox6",
    comentario: "modacomentario6",
    fecha: "modafecha6",
    modaValor: "modaValor6",
  },
  {
    id: "C)",
    multer: "moda7",
    preguntaForm: "mod7",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "modacheckbox7",
    comentario: "modacomentario7",
    fecha: "modafecha7",
    modaValor: "modaValor7",
  },
  {
    id: "D)",
    multer: "moda8",
    preguntaForm: "mod8",
    pregunta_nombre: "Correas y collares acorde POG/Guía Flex",
    checkbox: "modacheckbox8",
    comentario: "modacomentario8",
    fecha: "modafecha8",
    modaValor: "modaValor8",
  },
  {
    id: "E)",
    multer: "moda9",
    preguntaForm: "mod9",
    pregunta_nombre: "Tramos de ropa acorde POG/Guía Flex",
    checkbox: "modacheckbox9",
    comentario: "modacomentario9",
    fecha: "modafecha9",
    modaValor: "modaValor9",
  },
  {
    id: "F)",
    multer: "moda10",
    preguntaForm: "mod10",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "modacheckbox10",
    comentario: "modacomentario10",
    fecha: "modafecha10",
    modaValor: "modaValor10",
  },
  {
    id: "G)",
    multer: "moda11",
    preguntaForm: "mod11",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "modacheckbox11",
    comentario: "modacomentario11",
    fecha: "modafecha11",
    modaValor: "modaValor11",
  },
  {
    id: "H)",
    multer: "moda12",
    preguntaForm: "mod12",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "modacheckbox12",
    comentario: "modacomentario12",
    fecha: "modafecha12",
    modaValor: "modaValor12",
  },
  {
    id: "I)",
    multer: "moda13",
    preguntaForm: "mod13",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "modacheckbox13",
    comentario: "modacomentario13",
    fecha: "modafecha13",
    modaValor: "modaValor13",
  },
];
export const planohogarperro = [
  {
    id: "A)",
    multer: "moda14",
    preguntaForm: "mod14",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "modacheckbox14",
    comentario: "modacomentario14",
    fecha: "modafecha14",
    modaValor: "modaValor14",
  },
  {
    id: "B)",
    multer: "moda15",
    preguntaForm: "mod15",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "modacheckbox15",
    comentario: "modacomentario15",
    fecha: "modafecha15",
    modaValor: "modaValor15",
  },
  {
    id: "C)",
    multer: "moda16",
    preguntaForm: "mod16",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "modacheckbox16",
    comentario: "modacomentario16",
    fecha: "modafecha16",
    modaValor: "modaValor16",
  },
  {
    id: "D",
    multer: "moda17",
    preguntaForm: "mod17",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "modacheckbox17",
    comentario: "modacomentario17",
    fecha: "modafecha17",
    modaValor: "modaValor17",
  },
  {
    id: "E)",
    multer: "moda18",
    preguntaForm: "mod18",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "modacheckbox18",
    comentario: "modacomentario18",
    fecha: "modafecha18",
    modaValor: "modaValor18",
  },
  {
    id: "F)",
    multer: "moda19",
    preguntaForm: "mod19",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "modacheckbox19",
    comentario: "modacomentario19",
    fecha: "modafecha19",
    modaValor: "modaValor19",
  },
  {
    id: "G)",
    multer: "moda20",
    preguntaForm: "mod20",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "modacheckbox20",
    comentario: "modacomentario20",
    fecha: "modafecha20",
    modaValor: "modaValor20",
  },
];
export const planomdgato = [
  {
    id: "A)",
    multer: "moda21",
    preguntaForm: "mod21",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "modacheckbox21",
    comentario: "modacomentario21",
    fecha: "modafecha21",
    modaValor: "modaValor21",
  },
  {
    id: "B)",
    multer: "moda22",
    preguntaForm: "mod22",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "modacheckbox22",
    comentario: "modacomentario22",
    fecha: "modafecha22",
    modaValor: "modaValor22",
  },
  {
    id: "C)",
    multer: "moda23",
    preguntaForm: "mod23",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "modacheckbox23",
    comentario: "modacomentario23",
    fecha: "modafecha23",
    modaValor: "modaValor23",
  },
  {
    id: "D)",
    multer: "moda24",
    preguntaForm: "mod4",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "modacheckbox24",
    comentario: "modacomentario24",
    fecha: "modafecha24",
    modaValor: "modaValor24",
  },
  {
    id: "E)",
    multer: "moda25",
    preguntaForm: "mod25",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "modacheckbox25",
    comentario: "modacomentario25",
    fecha: "modafecha25",
    modaValor: "modaValor25",
  },
  {
    id: "F)",
    multer: "moda26",
    preguntaForm: "mod26",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "modacheckbox26",
    comentario: "modacomentario26",
    fecha: "modafecha26",
    modaValor: "modaValor26",
  },
  {
    id: "G)",
    multer: "moda27",
    preguntaForm: "mod27",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "modacheckbox27",
    comentario: "modacomentario27",
    fecha: "modafecha27",
    modaValor: "modaValor27",
  },
];
export const planohogargato = [
  {
    id: "A)",
    multer: "moda28",
    preguntaForm: "mod28",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "modacheckbox28",
    comentario: "modacomentario28",
    fecha: "modafecha28",
    modaValor: "modaValor28",
  },
  {
    id: "B)",
    multer: "moda29",
    preguntaForm: "mod29",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "modacheckbox29",
    comentario: "modacomentario29",
    fecha: "modafecha29",
    modaValor: "modaValor29",
  },
  {
    id: "C)",
    multer: "moda30",
    preguntaForm: "mod30",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "modacheckbox30",
    comentario: "modacomentario30",
    fecha: "modafecha30",
    modaValor: "modaValor30",
  },
  {
    id: "D)",
    multer: "moda31",
    preguntaForm: "mod31",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "modacheckbox31",
    comentario: "modacomentario31",
    fecha: "modafecha31",
    modaValor: "modaValor31",
  },
  {
    id: "E)",
    multer: "moda32",
    preguntaForm: "mod32",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "modacheckbox32",
    comentario: "modacomentario32",
    fecha: "modafecha32",
    modaValor: "modaValor32",
  },
  {
    id: "F)",
    multer: "moda33",
    preguntaForm: "mod33",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "modacheckbox33",
    comentario: "modacomentario33",
    fecha: "modafecha33",
    modaValor: "modaValor33",
  },
  {
    id: "G)",
    multer: "moda34",
    preguntaForm: "mod34",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "modacheckbox34",
    comentario: "modacomentario34",
    fecha: "modafecha34",
    modaValor: "modaValor34",
  },
];
export const modaCSN = [
  {
    id: "1",
    multer: "moda35",
    preguntaForm: "mo35",
    pregunta_nombre: "Se solicita al área de categorías",
    checkbox: "modacheckbox35",
    comentario: "modacomentario35",
    fecha: "modafecha35",
  },
  {
    id: "2",
    multer: "moda36",
    preguntaForm: "mod36",
    pregunta_nombre: "Se solicita al área de abasto",
    checkbox: "modacheckbox36",
    comentario: "modacomentario36",
    fecha: "modafecha36",
  },
  {
    id: "3",
    multer: "moda37",
    preguntaForm: "mod37",
    pregunta_nombre: "Se solicita al área de markting",
    checkbox: "modacheckbox37",
    comentario: "modacomentario37",
    fecha: "modafecha37",
  },
  {
    id: "4",
    multer: "moda38",
    preguntaForm: "mod38",
    pregunta_nombre: "Se solicita al área de compras",
    checkbox: "modacheckbox38",
    comentario: "modacomentario38",
    fecha: "modafecha38",
  },
  {
    id: "5",
    multer: "moda39",
    preguntaForm: "mod39",
    pregunta_nombre: "Se solicita al área de consumo interno",
    checkbox: "modacheckbox39",
    comentario: "modacomentario39",
    fecha: "modafecha39",
  },
  {
    id: "6",
    multer: "moda40",
    preguntaForm: "mod40",
    pregunta_nombre: "Se solicita al área de recursos humanos",
    checkbox: "modacheckbox40",
    comentario: "modacomentario40",
    fecha: "modafecha40",
  },
];
export const petcoZoo = [
  {
    id: "1",
    multer: "zoo1",
    preguntaForm: "zo1",
    pregunta_nombre: "Floorplan coincide físico vs PDF",
    checkbox: "zoocheckbox1",
    comentario: "zoocomentario1",
    fecha: "zoofecha1",
    zooValor: "zooValor1",
  },
  {
    id: "2",
    multer: "zoo2",
    preguntaForm: "zo2",
    pregunta_nombre: "Dueño de pasillo ejecutando tareas",
    checkbox: "zoocheckbox2",
    comentario: "zoocomentario2",
    fecha: "zoofecha2",
    zooValor: "zooValor2",
  },
];
export const planoacuario = [
  {
    id: "A)",
    multer: "zoo3",
    preguntaForm: "zo3",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "zoocheckbox3",
    comentario: "zoocomentario3",
    fecha: "zoofecha3",
    zooValor: "zooValor3",
  },
  {
    id: "B)",
    multer: "zoo4",
    preguntaForm: "zo4",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "zoocheckbox4",
    comentario: "zoocomentario4",
    fecha: "zoofecha4",
    zooValor: "zooValor4",
  },
  {
    id: "C)",
    multer: "zoo5",
    preguntaForm: "zo5",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "zoocheckbox5",
    comentario: "zoocomentario5",
    fecha: "zoofecha5",
    zooValor: "zooValor5",
  },
  {
    id: "D)",
    multer: "zoo6",
    preguntaForm: "zo6",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "zoocheckbox6",
    comentario: "zoocomentario6",
    fecha: "zoofecha6",
    zooValor: "zooValor6",
  },
  {
    id: "E)",
    multer: "zoo7",
    preguntaForm: "zo7",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "zoocheckbox7",
    comentario: "zoocomentario7",
    fecha: "zoofecha7",
    zooValor: "zooValor7",
  },
  {
    id: "F)",
    multer: "zoo8",
    preguntaForm: "zo8",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "zoocheckbox8",
    comentario: "zoocomentario8",
    fecha: "zoofecha8",
    zooValor: "zooValor8",
  },
  {
    id: "G)",
    multer: "zoo9",
    preguntaForm: "zo9",
    pregunta_nombre: "Hábitats de escritorio acorde a exhibiciones autorizadas",
    checkbox: "zoocheckbox9",
    comentario: "zoocomentario9",
    fecha: "zoofecha9",
    zooValor: "zooValor9",
  },
  {
    id: "H)",
    multer: "zoo10",
    preguntaForm: "zo10",
    pregunta_nombre: "Exhibiciones BOYU autorizadas",
    checkbox: "zoocheckbox10",
    comentario: "zoocomentario10",
    fecha: "zoofecha10",
    zooValor: "zooValor10",
  },
  {
    id: "I)",
    multer: "zoo11",
    preguntaForm: "zo11",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "zoocheckbox11",
    comentario: "zoocomentario11",
    fecha: "zoofecha11",
    zooValor: "zooValor11",
  },
];
export const planoreptil = [
  {
    id: "A)",
    multer: "zoo12",
    preguntaForm: "zo12",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "zoocheckbox12",
    comentario: "zoocomentario12",
    fecha: "zoofecha12",
    zooValor: "zooValor12",
  },
  {
    id: "B)",
    multer: "zoo13",
    preguntaForm: "zo13",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "zoocheckbox13",
    comentario: "zoocomentario13",
    fecha: "zoofecha13",
    zooValor: "zooValor13",
  },
  {
    id: "C)",
    multer: "zoo14",
    preguntaForm: "zo14",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "zoocheckbox14",
    comentario: "zoocomentario14",
    fecha: "zoofecha14",
    zooValor: "zooValor14",
  },
  {
    id: "D)",
    multer: "zoo15",
    preguntaForm: "zo15",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "zoocheckbox15",
    comentario: "zoocomentario15",
    fecha: "zoofecha15",
    zooValor: "zooValor15",
  },
  {
    id: "E)",
    multer: "zoo16",
    preguntaForm: "zo16",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "zoocheckbox16",
    comentario: "zoocomentario16",
    fecha: "zoofecha16",
    zooValor: "zooValor16",
  },
  {
    id: "F)",
    multer: "zoo17",
    preguntaForm: "zo17",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "zoocheckbox17",
    comentario: "zoocomentario17",
    fecha: "zoofecha17",
    zooValor: "zooValor17",
  },
  {
    id: "G)",
    multer: "zoo18",
    preguntaForm: "zo18",
    pregunta_nombre: "Hábitats acorde a exhibiciones autorizadas",
    checkbox: "zoocheckbox18",
    comentario: "zoocomentario18",
    fecha: "zoofecha18",
    zooValor: "zooValor18",
  },
  {
    id: "H)",
    multer: "zoo19",
    preguntaForm: "zo19",
    pregunta_nombre: "Grillera limpia, sin DOAS, con alimento",
    checkbox: "zoocheckbox19",
    comentario: "zoocomentario19",
    fecha: "zoofecha19",
    zooValor: "zooValor19",
  },
];
export const planoave = [
  {
    id: "A)",
    multer: "zoo20",
    preguntaForm: "zo20",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "zoocheckbox20",
    comentario: "zoocomentario20",
    fecha: "zoofecha20",
    zooValor: "zooValor20",
  },
  {
    id: "B)",
    multer: "zoo21",
    preguntaForm: "zo21",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "zoocheckbox21",
    comentario: "zoocomentario21",
    fecha: "zoofecha21",
    zooValor: "zooValor21",
  },
  {
    id: "C)",
    multer: "zoo22",
    preguntaForm: "zo22",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "zoocheckbox22",
    comentario: "zoocomentario22",
    fecha: "zoofecha22",
    zooValor: "zooValor22",
  },
  {
    id: "D)",
    multer: "zoo23",
    preguntaForm: "zo23",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "zoocheckbox23",
    comentario: "zoocomentario23",
    fecha: "zoofecha23",
    zooValor: "zooValor23",
  },
  {
    id: "E)",
    multer: "zoo24",
    preguntaForm: "zo24",
    pregunta_nombre: "Señalización de precios y promociones vigente",
    checkbox: "zoocheckbox24",
    comentario: "zoocomentario24",
    fecha: "zoofecha24",
    zooValor: "zooValor24",
  },
  {
    id: "F)",
    multer: "zoo25",
    preguntaForm: "zo25",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "zoocheckbox25",
    comentario: "zoocomentario25",
    fecha: "zoofecha25",
    zooValor: "zooValor25",
  },
  {
    id: "G)",
    multer: "zoo26",
    preguntaForm: "zo26",
    pregunta_nombre: "Hábitats acorde a exhibiciones autorizadas",
    checkbox: "zoocheckbox26",
    comentario: "zoocomentario26",
    fecha: "zoofecha26",
    zooValor: "zooValor26",
  },
  {
    id: "H)",
    multer: "zoo27",
    preguntaForm: "zo27",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "zoocheckbox27",
    comentario: "zoocomentario27",
    fecha: "zoofecha27",
    zooValor: "zooValor27",
  },
  {
    id: "I)",
    multer: "zoo28",
    preguntaForm: "zo28",
    pregunta_nombre: "Punteo de caducidades de productos en tramos",
    checkbox: "zoocheckbox28",
    comentario: "zoocomentario28",
    fecha: "zoofecha28",
    zooValor: "zooValor28",
  },
];
export const planoroedor = [
  {
    id: "A)",
    multer: "zoo29",
    preguntaForm: "zo29",
    pregunta_nombre: "Montaje a POG/Guía flex vigente",
    checkbox: "zoocheckbox29",
    comentario: "zoocomentario29",
    fecha: "zoofecha29",
    zooValor: "zooValor29",
  },
  {
    id: "B)",
    multer: "zoo30",
    preguntaForm: "zo30",
    pregunta_nombre: "Montajes respetan flujo de navegación",
    checkbox: "zoocheckbox30",
    comentario: "zoocomentario30",
    fecha: "zoofecha30",
    zooValor: "zooValor30",
  },
  {
    id: "C)",
    multer: "zoo31",
    preguntaForm: "zo31",
    pregunta_nombre: "Planogramas colocados en tramos",
    checkbox: "zoocheckbox31",
    comentario: "zoocomentario31",
    fecha: "zoofecha31",
    zooValor: "zooValor31",
  },
  {
    id: "D)",
    multer: "zoo32",
    preguntaForm: "zo32",
    pregunta_nombre: "Tramos sin sobre stock",
    checkbox: "zoocheckbox32",
    comentario: "zoocomentario32",
    fecha: "zoofecha32",
    zooValor: "zooValor32",
  },
  {
    id: "E)",
    multer: "zoo33",
    preguntaForm: "zo33",
    pregunta_nombre: "Señalización de precios y promociones vigentes",
    checkbox: "zoocheckbox33",
    comentario: "zoocomentario33",
    fecha: "zoofecha33",
    zooValor: "zooValor33",
  },
  {
    id: "F)",
    multer: "zoo34",
    preguntaForm: "zo34",
    pregunta_nombre: "Liquidaciones a final de tramo",
    checkbox: "zoocheckbox34",
    comentario: "zoocomentario34",
    fecha: "zoofecha34",
    zooValor: "zooValor34",
  },
  {
    id: "G)",
    multer: "zoo35",
    preguntaForm: "zo35",
    pregunta_nombre: "Hábitats acorde a exhibiciones autorizadas",
    checkbox: "zoocheckbox35",
    comentario: "zoocomentario35",
    fecha: "zoofecha35",
    zooValor: "zooValor35",
  },
  {
    id: "H)",
    multer: "zoo36",
    preguntaForm: "zo36",
    pregunta_nombre: "Mobiliario completo y tramos limpios",
    checkbox: "zoocheckbox36",
    comentario: "zoocomentario36",
    fecha: "zoofecha36",
    zooValor: "zooValor36",
  },
  {
    id: "I)",
    multer: "zoo37",
    preguntaForm: "zo37",
    pregunta_nombre: "Punteo de caducidades de productos en tramos",
    checkbox: "zoocheckbox37",
    comentario: "zoocomentario37",
    fecha: "zoofecha37",
    zooValor: "zooValor37",
  },
];
export const ZOOCSN = [
  {
    id: "1",
    multer: "zoo38",
    preguntaForm: "zo38",
    pregunta_nombre: "Se solicita al área de categorías",
    checkbox: "zoocheckbox38",
    comentario: "zoocomentario38",
    fecha: "zoofecha38",
  },
  {
    id: "2",
    multer: "zoo39",
    preguntaForm: "zo39",
    pregunta_nombre: "Se solicita al área de abasto",
    checkbox: "zoocheckbox39",
    comentario: "zoocomentario39",
    fecha: "zoofecha39",
  },
  {
    id: "3",
    multer: "zoo40",
    preguntaForm: "zo40",
    pregunta_nombre: "Se solicita al área de marketing",
    checkbox: "zoocheckbox40",
    comentario: "zoocomentario40",
    fecha: "zoofecha40",
  },
  {
    id: "4",
    multer: "zoo41",
    preguntaForm: "zo41",
    pregunta_nombre: "Se solicita al área de compras",
    checkbox: "zoocheckbox41",
    comentario: "zoocomentario41",
    fecha: "zoofecha41",
  },
  {
    id: "5",
    multer: "zoo42",
    preguntaForm: "zo42",
    pregunta_nombre: "Se solicita al área de consumo interno",
    checkbox: "zoocheckbox42",
    comentario: "zoocomentario42",
    fecha: "zoofecha42",
  },
  {
    id: "6",
    multer: "zoo43",
    preguntaForm: "zo43",
    pregunta_nombre: "Se solicita al área de recursos humanos",
    checkbox: "zoocheckbox43",
    comentario: "zoocomentario43",
    fecha: "zoofecha43",
  },
];
